### ISSUE TITLE
Default value를 지원하지 않는 이유 질문

### ISSUE THREAD

**Issue by WallabyStuff** [forXifLess/LinkNavigator#41]
안녕하세요 LinkNavigator 잘 사용하고 있는 한국 유저입니다!
우선 좋은 라이브러리 만들어 주셔서 대단히 감사드립니다. (덕분에 삶의 질이 상승하였어요😆)

다름이 아니라 LinkNavigator를 사용하면서 필요했던 새로운 기능을 구현 후 PR을 보내려고 하는데요,
그 전에 default value를 지원하지 않는 이유가 따로 있는지 여쭙습니다.

새로운 기능에 parameter값이 많아서 default value를 지원하려고 하는데 기존 코드를 보니 모두 default value를 지원하지 않더라구요.
```swift
extension LinkNavigatorType { ... }
```
에서 default value를 지원하도록 우회해주면 사용하는 클라이언트 입장에서 항상 입력해 줘야하는 path나 웬만해서는 true로 설정하고 사용하는 isAnimated parameter에 대해서 굳이 작성해주지 않아도 되지 않을까 생각합니다.

물론 개별적으로 LinkNavigatorType를 extension 해서 구현해 줄 수 있겠습니다만 라이브러리 자체에서 지원해준다면 훨 좋은 사용자 경험이 되지 않을까요?

**Comment by interactord** [comment]
문의주셔서 너무나 감사합니다.
저희도 DefaultValue를 원래 지원했습니다만, 프로토콜기반으로 작업하다보니 프로토콜 갯수가 너무 많아지는 결과를 초래했습니다.

디폴트로 지원하는 문제중 하나는 여러유저가 각자의 프로잭트에서 사용하는 빈도가 너무나 디양한점을 획일화 시키는게 아닌가 싶었습니다.

아이디어 주신대로 익스텐션으로 제공할 수 있는 PR을 가지고 같이 논의해보도록하죠

언제나 환영입니다
