### ISSUE TITLE
Deprecated LinkItem class

### ISSUE THREAD

**Issue by r0otx** [forXifLess/LinkNavigator#44]
Hello, thank you for this beautiful library. I'm have warning if use Link Item with params.

```
            navigator.next(
                linkItem: LinkItem(
                    path: AppScreens.otp.path,
                    items: PhoneNumberParam(phoneNumber: text)
                        .encoded()),
                isAnimated: true)
```

`'init(path:items:)' is deprecated: Please use init(path:itemsString:isBase64EncodedItemsString:) instead.`

How I can fix it?

**Comment by interactord** [comment]
hi @r0otx 

Thank you for using our library.  
  
We have made additional improvements for a better experience.  
  
Please refer to the method below. 

![image](https://github.com/user-attachments/assets/4b6b6ad9-eec1-4a58-a882-90615d7ec312)

**Comment by interactord** [comment]
The link below is an example of an enterprise sample created using TCA, Tuist, and Clean Architecture. 

I apologize for the delayed ReadMe update. 

https://github.com/interactord/favorite/tree/main
