### ISSUE TITLE
The page is abnormally rolled back

### ISSUE THREAD

**Issue by lleihai123** [forXifLess/LinkNavigator#45]
WindowGroup {
            navigator.launch(paths: [RootView.viewKey], items: [:])
                .navigationBarHidden(true)
                .edgesIgnoringSafeArea(.all)
                .interactiveDismissDisabled(false)
                .onOpenURL { _ in
                    // deep links
                }
        }
        
        The phone pushed the background, and then back to the front, the jump page, are back to the root page

**Comment by 97chos** [comment]
Hello, @lleihai123 .
Could you please record a video of the issue being reproduced and upload it as a video?

**Comment by lleihai123** [comment]
import SwiftUI
import LinkNavigator

let CSRouter: LinkNavigator  = LinkNavigator(dependency: AppDependency(),
                                             builders: AppRouterGroup().routers)
                                             
struct HomeRouteBuilder: RouteBuilder {
  var matchPath: String { RootView.viewKey }

  var build: (LinkNavigatorType, [String: AnyObject], DependencyType) -> MatchingViewController? {
    { navigator, items, dependency in
      return WrappingController(matchPath: matchPath) {
          RootView()
      }
    }
  }
}

@main
struct ConciseScannerApp: App {
    @UIApplicationDelegateAdaptor(AppDelegate.self) var appDelegate
    @Environment(\.scenePhase) var scenePhase

    var body: some Scene {
        WindowGroup {
            CSRouter.launch(paths: [RootView.viewKey], items: [:])
                .navigationBarHidden(true)
                .edgesIgnoringSafeArea(.all)
                .interactiveDismissDisabled(false)
                .onOpenURL { _ in
                    // deep links
                }
        }.onChange(of: scenePhase) { newScenePhase in
            switch newScenePhase {
            case .active:
                CSEventCenter.shard.appEvent.value = EventAction(eventType: .active)
                break
            case .inactive:
                CSEventCenter.shard.appEvent.value = EventAction(eventType: .inactive)
                break
            case .background:
                CSEventCenter.shard.appEvent.value = EventAction(eventType: .background)
                break
            @unknown default:
                print("default")
            }
        }
    }
}

https://github.com/user-attachments/assets/fc5881ac-0820-4ae5-87dc-39ee57f7227e

**Comment by interactord** [comment]
hi! @lleihai123 ~

Thank you for registering the issue. Glass will do its best to address the problem you are facing. First of all, it is difficult to assess the situation based solely on the video and code provided.

After reviewing the video, it appears that sharing the commercial code with us may be challenging.

Therefore, please create an example code that demonstrates the issue with Grasso, upload it to GitHub, and share the repository with us.

We will do our utmost to assist you. Thank you very much.

**Comment by interactord** [comment]
Hello @lleihai123 

As mentioned in the ReadME, only one identical ID(matchPaths) can be used on the page in the navigator. If you register multiple IDs, please consider replacing our library.
