### ISSUE TITLE
.navigationBarHidden(true)

### ISSUE THREAD

**Issue by lleihai123** [forXifLess/LinkNavigator#46]
Gesture return no more

**Comment by 97chos** [comment]
Hi, @lleihai123 .

Could you let me know which gesture is not working?
And is it written with the same code as the one you posted in [the issue](https://github.com/forXifLess/LinkNavigator/issues/45#issue-2601570035)?

**Comment by lleihai123** [comment]
[TestRouter.zip](https://github.com/user-attachments/files/17468961/TestRouter.zip)
This demo, feedback 3 questions, please take a look

**Comment by lleihai123** [comment]
@97chos  demo has been uploaded, please take a look.

**Comment by interactord** [comment]
The Gesture Back function is operating correctly. 

Could you please specify which function you are referring to that is not allowed? 

I would appreciate it if you could provide more details. 


https://github.com/user-attachments/assets/7c1390fe-dc0c-4b50-9dac-024a5a9ef606

**Comment by interactord** [comment]
Hello @lleihai123 

Please create a file and add the code below. 

UINavigationControllerExtension.swift

`
import UIKit

extension UINavigationController: ObservableObject, UIGestureRecognizerDelegate {

  // MARK: Open

  override open func viewDidLoad() {
    super.viewDidLoad()
    interactivePopGestureRecognizer?.delegate = self
    navigationBar.isHidden = true
  }

  // MARK: Public

  public func gestureRecognizerShouldBegin(_: UIGestureRecognizer) -> Bool {
    viewControllers.count > 1
  }
}

`

**Comment by lleihai123** [comment]
Problem solved, thank you very much
