### ISSUE TITLE
How use DI Container?

### ISSUE THREAD

**Issue by r0otx** [forXifLess/LinkNavigator#48]
Hello, I can't find examples, how use DI container? I can use ObservableObject in my ViewModel and pass him in view? I want create ProfileRepository inject him in VM from DI, change params from VM and show changes in ui.

**Comment by interactord** [comment]
thank you @r0otx 

Thank you for letting us know what we missed. 

I will update the example code based on your inquiry and share it with you. 

It shouldn't take long.

**Comment by interactord** [comment]
hi! @r0otx 

As you requested, I utilized diContainer to create a SharedViewModel, which provides a secure method for sharing various types of data. Additionally, you can leverage a range of service adapters, including UseCase.

Among the example projects, please refer to the project at the URL below.

https://github.com/forXifLess/LinkNavigator/tree/main/Examples/SingleNavigator/02-SingleEventSubscriber

If you have any questions, please feel free to leave a comment.

Thank you.
