### ISSUE TITLE
UINavigationControllerExtension       navigationBar.isHidden  Why is the default true

### ISSUE THREAD

**Issue by 350887156** [forXifLess/LinkNavigator#49]
UINavigationControllerExtension       

navigationBar.isHidden  Why is the default true

This will cause the navigation in my project to be lost.

**Comment by interactord** [comment]
I apologize for the oversight regarding that matter. I will restore it and add a new tag.

**Comment by interactord** [comment]
HI! @350887156 
Please update the package to version 1.3.0. 

thank you
